# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6ef2d88252e5cfa9a4039ed0cd2676e53874adb18b81fda408617f79cf71e852621e2bb800256034bd685a967bd85e14dc0e5b42ae215dfd501721d3fb924e49

test:
  secret_key_base: a023a514122b535b9a222de17ca53eaa44e0b7fb51dae14b60f84b9d58a13bdd96d09bf0c4fc680fe41c463e243ed55ad36e5ffa625d53fed068ee1c19bcecac

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
